#define crud functions for user table, these functions interact with the db using sqlalchemy Sessions

from sqlalchemy.orm import Session
import models, schemas

#create new user

def create_user(db:Session,user:schemas.UserCreate):
  db_user = models.User(
    name= user.name,
    age=user.age,
    location= user.location,
    nid = user.nid,
    citizenship_number = user.citizenship_number
  )
  db.add(db_user)
  db.commit()
  db.refres(db_user) #refresh to get autogenerated fields like id
  return db_user

def get_all_users(db:Session):
  return db.query(models.user).all() # returns list of ORM objects

def update_user(db: Session, nid: int, updated_user: schemas.UserCreate):
    user = db.query(models.User).filter(models.User.nid == nid).first()
    if not user:
        return None
    user.name = updated_user.name
    user.age = updated_user.age
    user.location = updated_user.location
    user.nid = updated_user.nid
    user.citizenship_number = updated_user.citizenship_number
    db.commit()
    db.refresh(user)
    return user

def delete_user(db: Session, nid: int):
    user = db.query(models.User).filter(models.User.nid == nid).first()
    if not user:
        return None
    db.delete(user)
    db.commit()
    return user